# pretraining in other data
python ./src/main.py \
    --is_pretrained \
    --method random \
    --selected_k 3\
    --prefix /root/LaiDA/pretrain_data/ \
    --inst_prefix /root/LaiDA/pretrain_data/instruction/ \
    --do_train \
    --seed 42 \
    --dataset_dir ./pretrain_data \
    --model_name_or_path /hy-tmp/models/qwen/Qwen2-7B-Instruct \
    --finetuning_type lora \
    --template qwen \
    --lora_target all \
    --lora_rank 32 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --logging_steps 40 \
    --save_steps 500 \
    --val_size 0.1 \
    --learning_rate 8e-5 \
    --num_train_epochs 3.0 \
    --bf16